services:
  contiwatch-agent:
    image: contiwatch:latest
    container_name: contiwatch-agent
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/buzlab/docker/contiwatch_agent/data:/data
    environment:
      CONTIWATCH_ADDR: ":8080"
      CONTIWATCH_CONFIG: "/data/config.json"
      CONTIWATCH_AGENT: "true"
      CONTIWATCH_AGENT_TOKEN: "PUT_32_CHAR_TOKEN_HERE"
      TZ: "Europe/Warsaw"
      PUID: "1026"
      PGID: "100"
    restart: unless-stopped
