services:
  contiwatch-agent:
    image: ghcr.io/pbuzdygan/contiwatch:latest
    container_name: contiwatch-agent
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - contiwatch_agent_data:/data
    environment:
      # Both "CONTIWATCH_AGENT" env are MUST HAVE for REMOTE AGENT instance
      # Remote agent instance has limited funtions compared to standard Contiwatch instance and its used to monitor remote Docker hosts
      CONTIWATCH_AGENT: "true"
      CONTIWATCH_AGENT_TOKEN: "PUT_32_CHAR_TOKEN_HERE"
      # Default internal port can be changed - helpful when running in "network_mode: host" or other "direct IP" setups
      CONTIWATCH_ADDR: ":8080"
      CONTIWATCH_CONFIG: "/data/config.json"
      TZ: Europe/Warsaw
    restart: unless-stopped

volumes:
  contiwatch_agent_data: